### ISSUE TITLE
Room Editor - Custom assets picker/window

### ISSUE THREAD

**Issue by Gear-Studio** [YoYoGames/GameMaker-Feature-Requests#1020]
### Is your feature request related to a problem?

Would be great to have a special container for assets to select from and place into the room. If you got 1000+ sprites/objects it's hard to expand the assets list and search for specific one. I wish to have my own asset window collection.

### Describe the solution you'd like

For example I can pick 10 sprites from assets list and put it to my own asset container to use it in room editor.

**Comment by gavsmart** [comment]
When we introduced the Asset Browser we added the ability to have multiple of these open, each able to have a different filter (asset type, tags, and/or search). This might well do what you are after :) 


![Image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/13905932/a53c295d-f4de-4344-95f2-b803fa2566f1)

**Comment by iampremo** [comment]
When we introduced the Asset Browser we added the ability to have multiple of these open, each able to have a different filter (asset type, tags, and/or search). This might well do what you are after :) 


![Image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/13905932/a53c295d-f4de-4344-95f2-b803fa2566f1)

**Comment by gnysek** [comment]
Tags seems to be best solution here:
As example, I've got 3 asset browsers open at once, one with all resources, one with tag `filter1` and one with rooms and shaders:
![obraz](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/524094/e757ba0d-a0d4-41aa-87e5-905168dedbc9)
