### ISSUE TITLE
Request streamline of asset creation

### ISSUE THREAD

**Issue by RetroSorcery** [YoYoGames/GameMaker-Feature-Requests#1048]
### Is your feature request related to a problem?

Request streamline of asset creation.

When creating an asset of any type you need to specify what type you want. If I am clicking on 'Shader' for example and select 'Create', it's pretty safe to assume that I want a shader. But the user must then specify again, what type of asset they want.

![select](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/96849578/f7a9e830-dbac-45ec-a10e-92d902c0ca31)

### Describe the solution you'd like

Right click an asset type select "Create", then create an asset of that type.

**Comment by Mortisanti** [comment]
It's funny that you requested this, as it's how GameMaker Studio 2 used to be. [Example](https://www.youtube.com/watch?v=izNXbMdu348&t=52s)

Perhaps they could add it back as an option in Preferences > Asset Browser.

**Comment by gnysek** [comment]
1) As you can rename/delete folders and put any resource type (so you can have sprites in `Shaders` group) it doesn't have sense IMO
2) You can right click on existing resource, and option `Create <same resource type>` is then available, which does what you say.

**Comment by attic-stuff** [comment]
> Yeah, it's strange they changed it to this 'new' way. It's not a show-stopper by any stretch. More of an annoyance if anything.

it has been this way for nearly three years now, its not really "new" haha. the change from folders of specific asset types to just _groups_ of any asset was imo huge and great and cool, and the ability to create specific assets by right clicking on another asset is still in the ide.

**Comment by RetroSorcery** [comment]
> > Yeah, it's strange they changed it to this 'new' way. It's not a show-stopper by any stretch. More of an annoyance if anything.
> 
> it has been this way for nearly three years now, its not really "new" haha. the change from folders of specific asset types to just _groups_ of any asset was imo huge and great and cool, and the ability to create specific assets by right clicking on another asset is still in the ide.

I see what you mean now. I didn't realise you can now delete any group, including the existing ones and then arrange your project however you see fit.

That is quite handy now that I see it.

**Comment by gnysek** [comment]
> I didn't realise you can now delete any group, including the existing ones

don't forget that you can put any resource type into any group too

**Comment by jackerley** [comment]
Folders are no longer type specific so this can't really be done.
