### ISSUE TITLE
Private Variables

### ISSUE THREAD

**Issue by LesserGoldfish** [YoYoGames/GameMaker-Feature-Requests#1067]
### Is your feature request related to a problem?

By default, game maker does not have an easy way of encapsulating code, requring messy work arounds such as putting private varaibles and methods into a struct. While having every instance variable exposed by default is simpler for newer programmers, it would be nice to have a way to keep varaibles which rarely, or never, interact outside of their instance hidden.

### Describe the solution you'd like

A new keyword "private" would be added which would be used in a similar way to "static", added before the variable name to make it private to the instance it was created in. This means that, by default, instance variables remain exposed to keep things simple for never developers but can be used by those more advanced

### Describe alternatives you've considered

Another possible impelmentation is through jsdoc comments, which would indicate to feather to hide a varaible or method from the auto complete and throw an error if a user does attempt to access a private variable outside of its scope

**Comment by katsaii** [comment]
You might be able to replicate private variables if GML ever gets closures (see: https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/992). I reckon this would be a nicer solution than bloating the language with another keyword like `private`.

Rendered:
```js
function Vec2(x_, y_) constructor {
  var xPos = x_; // private vars
  var yPos = y_;
  
  static getX = () => {
    // getter for private `xPos` var
    return xPos;
  };
  
  static getY = () => {
    // getter for private `yPos` var
    return yPos;
  };
}
```

**Comment by stuckie** [comment]
We have no plans to add this to GML.
