### ISSUE TITLE
Add linux IDE support

### ISSUE THREAD

**Issue by Shadowblitz16** [YoYoGames/GameMaker-Feature-Requests#1068]
### Is your feature request related to a problem?

Please release game maker studio ide for linux.

### Describe the solution you'd like

Release linux compatible gamemaker IDE that allows linux users to make games.

### Describe alternatives you've considered

I have tried using the beta version of the ubuntu editor but it doesn't work
I have also tried using steam proton

### Additional context

Consider using app image or official ppa to bundle it.
we want the dependencies to be able to be used on distro's that aren't strictly ubuntu <version here>

**Comment by stuckie** [comment]
This is more of a bug than a feature request, please send in a ticket with more information.
We are only supporting Ubuntu at the moment and it is only available as a Beta package.

**Comment by Shadowblitz16** [comment]
> This is more of a bug than a feature request, please send in a ticket with more information. We are only supporting Ubuntu at the moment and it is only available as a Beta package.

No it's a request to put more effort into a cross platform ide.
There are only bugs because you guys don't care.
