### ISSUE TITLE
Free Windows Export Option

### ISSUE THREAD

**Issue by Tf2dude** [YoYoGames/GameMaker-Feature-Requests#1073]
### Is your feature request related to a problem?

Right now, you need to purchase a license to export gms2 games in Windows. This is a big problem when you’re working on a game and don’t have a lot of money.

### Describe the solution you'd like

I think the solution is that Windows exporting should be free.

**Comment by gnysek** [comment]
I'm not sure when you last checked GM prices, but to export games on Windows you need to pay only 5 USD (and then you can use export for one month), but for some countries it's even cheaper - for example in Brazil it's just 1.46 USD (as prices are adjusted per country salaries).

**Comment by stuckie** [comment]
This is not something that we are considering.
