### ISSUE TITLE
Multi Game Launcher

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1099]
Adds the ability to switch the game that is currently running

**Comment by FoxyOfJungle** [comment]
How exactly would that work? I'm curious. Thanks

**Comment by xotmatrix** [comment]
I know this is already on the roadmap and was discussed at a recent roundtable meeting. I'm going to assume the hand-off between games will be relatively seamless which would require display modes to be decided and visible to or asserted for a launched game before it starts running. Will this allow games to read a configuration file before opening a display to start in a preferred mode (fullscreen, windowed, borderless) without any awkward display changes after starting? Many Windows games have launchers for precisely this purpose.

**Comment by gnysek** [comment]
@FoxyOfJungle @xotmatrix it seems to be in yesterdays beta:


![Image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/524094/6b80d1a7-88f4-4f94-befb-d53e6fdd79ae)

**Comment by time-killer-games** [comment]
huge shout out to YoYoGames a very big thank you for adding this!!! 💃
