### ISSUE TITLE
Typed Handles p1

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1105]
Currently many internal GM functions will return a handle to a runtime object that is just a number, this is an index to an internal data structure where the object lives. This number does not convey information on what it is a handle for (the type of the object) so no checking can be made to ensure that the user is using the correct handle for this function, as long as an object of that type with that handle exists it will use that one. This makes it too easy to make mistakes that lead to odd effects.

This change will start to introduce some type information into the handles that GM functions return so that they can be type checked and improve users code, making it easier to find problems with the code.

In this phase we will be bringing support for type checking on 

* Data Structures - the `ds_xxx` family of functions
* Asset References - all names assets from the IDE asset tree will be references, and dynamically created resources.

**Comment by WangleLine** [comment]
Very mysterious 👀

**Comment by gnysek** [comment]
Seems it's about `ds_xxx` stuff

**Comment by gnysek** [comment]
`ds_xxx` stuff **confirmed in beta** and works nicely:

```gml
var _list = ds_list_create();
var _map = ds_map_create();

show_debug_message(ds_exists(_map, ds_type_list));
show_debug_message(ds_exists(_map, ds_type_map));
show_debug_message(ds_exists(_list, ds_type_list));
show_debug_message(ds_exists(_list, ds_type_map));
```

shows `1,1,1,1` in monthly, but `0,1,1,0` in 2023.800 already.

Also:
```gml
a = ds_map_create();

show_debug_message(a);
show_debug_message(string(a));
show_debug_message(real(a));
show_debug_message(typeof(a));
```
shows:
```
ref 0
ref 0
0
ref
```
(and since refs are taken from same pool, there won't be another "ref 0", but next map/list/grid/stack/etc will be "1" and so on...). This makes any `ds_xxx` to have unique name among whole GM and allows to detect DS type:
```gml
function ds_get_type(_ds) {
    if (ds_exists(_ds, ds_type_map)) return ds_type_map;
    if (ds_exists(_ds, ds_type_list)) return ds_type_list;
    if (ds_exists(_ds, ds_type_stack)) return ds_type_stack;
    if (ds_exists(_ds, ds_type_grid)) return ds_type_grid;
    if (ds_exists(_ds, ds_type_queue)) return ds_type_queue;
    if (ds_exists(_ds, ds_type_priority)) return ds_type_priority;
    return undefined;
}
```

**Comment by WangleLine** [comment]
it might be cool if these typed handles would say ref_sprite [n], ref_ds_map [n] etc. when stringified

**Comment by W1llth0t** [comment]
hmm but what about multithreading support?
