### ISSUE TITLE
Open in external Editor

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1108]
Allows users to specify which applications should be used to open certain file types

**Comment by gnysek** [comment]
Sounds like return of some good old preferences:

![Image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/524094/c4f880c6-f69c-49c2-aad5-b09fe029eccf)

**Comment by flashice2030** [comment]
That's the most important!!
