### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1113]

**Comment by FoxyOfJungle** [comment]
I'm VERY interested in this. Is there any information (even minimal) of what will be possible with this feature?

If that's what I'm thinking, it would be interesting if GameMaker had a list of "built-in packages" (which will be links to GitHub repositories) where I can import the project directly into GameMaker in a few clicks.

For example, you could list the Steamworks extension!
https://github.com/YoYoGames/GMEXT-Steamworks

And other cool ones like Scribble.

Then the GM would do a `git clone` (or download from "Releases") and automatically import it into the project. Being able to remove and/or update it at any time too (with a confirmation message).

**Comment by gnysek** [comment]
From what it was said, it will use either `Conan` or `npm` and would allow to define our own servers with sources, so I believe that sth similar to what you describe should be possible, but we need to wait for more info probably.
This feature seems to be pre-requirement for both new runtime and prefabs features from what I understand.

**Comment by W1llth0t** [comment]
hmm but what about multithreading support?

**Comment by SanyaShanin** [comment]
It is in beta now, so what is it? Is there any description of this feature?

**Comment by gnysek** [comment]
@SanyaShanin actually, for now it have nearly no use. It would be used by New Runtime open beta (when it would start in not that far future), and by "prefabs" open beta in one of later versions. So it's required to test some features in next few months, but as for today it rather doesn't allow anything special.

**Comment by TERNOX** [comment]
So.. what is it?

**Comment by gnysek** [comment]
@TERNOX I've wrote what it is before your comment. It allows to update things that are required by New Runtime. Seems that until NR is in "closed beta" it have no use for most of GM users, that's why there's no more details.
