### ISSUE TITLE
Sorting draw order of instances in a layer

### ISSUE THREAD

**Issue by Ailwuful** [YoYoGames/GameMaker-Feature-Requests#1124]
### Is your feature request related to a problem?

I know there is a deterministic order that things in a layer put in the room are drawn, since you can change that order in this list:
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/93070196/5d34adaa-3099-4eed-8c7d-0bc59a8e725d)
You can currently change the order things are drawn by changing depth, but then you lose a lot of layer functionality and organization. You can also custom call the draw event of instances in the order you want, but that can be annoying. 

I would absolutely love if we had a function to sort draw order of instances that are in a certain layer. That would make so many things easier.

### Describe the solution you'd like

The function could be very similar to array_sort, maybe layer_instance_sort? You would only need to give the layer id/name as an argument and a method to define how to sort the instances, in which element1 and element2 are ids of the instances. For example:
`var _sort_method = function(elm1, elm2) {
 return elm1.y - elem2.y;
};
layer_instance_sort("Instances", _sort_method);`

That would sort instances in a similar way of depth = -y;

**Comment by jackerley** [comment]
Within a layer we don't enforce an order, and aren't planning on changing this. Layers are the way that you should be enforcing draw order.

**Comment by Ailwuful** [comment]
> Within a layer we don't enforce an order, and aren't planning on changing this. Layers are the way that you should be enforcing draw order.

I'm sorry. I don't quite understand this. Instances in the same layer do have an order in which they are drawn which is always maintained, even if you change rooms. The request is if that order can somehow be changed. Are you saying that's not something that could be done?
We lose a lot of convenient layer functionality by putting a lot of instances in different layers, like assigning a shader to a layer, a script, or grabbing elements, etc.

**Comment by JujuAdams** [comment]
> What I understand from your response is that there is no defined order

Correct. YYG are reserving the right to change that at any point.

**Comment by EmWouters** [comment]
Still baffling to me this isn't at least an optional feature we could get...
maintain_order(descending?) or something per step...
