### ISSUE TITLE
Mention in manual that collision mask is restricted by sprite canvas

### ISSUE THREAD

**Issue by Tazdraperm** [YoYoGames/GameMaker-Feature-Requests#1134]
### Is your feature request related to a problem?

Currently in Sprite Editor, if you set collision mask to the size that is larger than sprite's canvas, the mask will be cropped to canvas size. While this is obvious for Precise collision mask, it's not very intuitive behaviour in case of other collision mask types (Rectangle, Ellipse, Diamond).
I suggest explicitly stating that behaviour in manual.

### Describe the solution you'd like

Update the manual with relevant information. In the Sprite Editor, improve the indication of which parts of the collision shape will be actually used for collisions.

**Comment by KormexGameMaker** [comment]
After some testing, it appears this only applies to precise masks (precise, ellipse, etc). Rectangle and rectangle with rotation masks can go outside of the canvas just fine. So, it's quite possible this is a bug rather than undocumented functionality

**Comment by dsk80004** [comment]
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/4e543f10-6f12-4f01-874b-ad04caba55cf)
https://gyazo.com/db90450ce220af2bef1826a73ad4e468.mp4

**Comment by jackerley** [comment]
We will assign this to be clarified in the manual
