### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1145]
This extension provides you with a cross-platform experience of the Bluetooth technology. It is compatible with Windows|macOS|iOS|Android for Bluetooth Low Energy and with Windows|Android for Bluetooth Classic.

**Comment by DiasFranciscoA** [comment]
Both the documentation and the repo are now finished and public at this point here:

https://github.com/YoYoGames/GMEXT-Bluetooth

wiki is also finished!

NOTE: marketplace publish is still pending.
