### ISSUE TITLE
InAppUpdate

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1156]

**Comment by dev816** [comment]
I've done it for a long time, let me pass the sources

**Comment by Glim888** [comment]
Here you are (from 2020):

https://github.com/Glim888/GooglePlay-Review-API-for-GameMakerStudio-v2.3.1

**Comment by dev816** [comment]
No, but I have my own solution and yoyo has also released its extension
 
 
С Уважением Бочаров Антон.
