### ISSUE TITLE
Huawei

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1158]

**Comment by Glim888** [comment]
I guess you mean HuaweiAppGallery? I am registered there. I get 1% of google play traffic. I would not suggest entering this market nor creating an extension for it. :)

**Comment by flashice2030** [comment]
Huawei , Wei chat app , XiaoMi ,TaoBao, Oppo and Vivo  ,etc ,  in china ,All these MiniWebGame need GameMaker in future.
