### ISSUE TITLE
Function to keep track of how many of each DS is active

### ISSUE THREAD

**Issue by CyanSorcery** [YoYoGames/GameMaker-Feature-Requests#1160]
### Is your feature request related to a problem?

Currently there is no function to see how many of each DS type you have created, meaning that I've been keeping track of them with a debug function that just iterates over hundreds of numbers with ds_exists. However, due to the upcoming stronger typing of DS types, this wont work anymore, since the types will be different.

### Describe the solution you'd like

A function that lets you know how many of each type of DS you have in the game at any given time. Ideally, there could be other functions to keep track of vertex buffers, formats, and the like too (pretty much any type of dynamic resource, to help better keep track of memory leaks.)

### Additional context

and while we're at it, maybe there could be functions to see if a vertex buffer or format exists? I know there's at least one place in my code where a vertex buffer has a chance of being deleted earlier in the code, so I just call vertex_delete_buffer in a try/catch and if it fails I can assume it was deleted earlier, which isn't ideal imo

**Comment by tabularelf** [comment]
If you just want a count of how many X resource is there in total... There are already functions built in for this.
`debug_event("ResourceCounts")` - Returns a struct with the current count of data structures, buffers, surfaces, audio emitters, particles (systems, emitters, types), time sources and game assets. The only thing that it doesn't have is:

- Showing other resource counts (such as vertex buffers, vertex formats)
- A way to silent the output to the console (as it currently dumps it into the console as well)

https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Debugging/debug_event.htm

**Comment by Alphish** [comment]
@tabularelf But... but you *can* silent the output to the console with the optional "silent" parameter! It's in the very manual page you listed, too! ^^'

But yeah, it doesn't list all resources, but it does list counts of DS data structures and a bunch of others. I guess an alternative feature would be including the additional resources (like vertex buffers and such) in the ResourcesCount.

**Comment by tabularelf** [comment]
Huh... I had thought it was a thing, but it didn't work for me before O.o

**Comment by stuckie** [comment]
As commented above, we already have this functionality.
