### ISSUE TITLE
Open more than One project at time

### ISSUE THREAD

**Issue by jobit696** [YoYoGames/GameMaker-Feature-Requests#1172]
### Is your feature request related to a problem?

In game maker studio 2 we can't open more than One project at time 

### Describe the solution you'd like

It Will be great to have the possibility to open more than one project at time   ( using One instance of gamemaker.exe  )  so we can access and Copy our code and do other stuffs One project to another and having It on different tabs on the top of the workSpace area like: | project1 | | project2 | | project3 | . Maybe with the possibility to use drag and drop actions to share resource One project to another

**Comment by Alphish** [comment]
I'm not sure having multiple different GM projects open in the same GM instance would be the best use of YYG resources (assuming it's a non-trivial thing).

If you just need to copy-paste a few code snippets around, you can open multiple GM instances with different project each.

If you need to copy assets in bulk, you may create a [Local Package](https://manual.yoyogames.com/#t=IDE_Tools%2FLocal_Asset_Packages.htm) from one project, then import it in another project. Upcoming Prefabs feature may or may not provide even better options for local code re-use, depending how they're implemented.

In general, the only time I feel the need to open multiple projects at the same time is when I want to copy stuff around, and this situation happens infrequently enough that copy-paste between GM instances or creating a simple Local Package isn't too much of a hassle. But also that's me.

**Comment by jackerley** [comment]
Just open two IDEs?
