### ISSUE TITLE
Option for new debug overlay to be minimized by default

### ISSUE THREAD

**Issue by RhyminGarfunkle** [YoYoGames/GameMaker-Feature-Requests#1175]
### Is your feature request related to a problem?

I generally run games in debug mode unless I'm testing something in YYC, because it shows the entire script section when there's a crash and makes it easy to set breakpoints and directly check the value of specific variables. With the new debug overlay, I now need to go through an extra step each time I run a game, to minimize the new debug overlay.

It's great to have all this new information available if I need it, but most of the time it's just in the way, obnoxiously taking up a massive portion of my screen.

### Describe the solution you'd like

Create an option, either in the IDE or the game settings, to have the new debugger overlay minimized by default.

**Comment by RhyminGarfunkle** [comment]
I'd also be fine with storing the debug output window's state. So if I left it open, it'd be open the next time I ran the debugger, and if I minimized it, it'd start collapsed next time it ran.

**Comment by FoxyOfJungle** [comment]
I totally agree. It's not often that I want detailed debugging information - with FPS, batches, texture swaps, Step and Draw usage being the most important IMO. So if it's minimized, show those. If I want detailed information I just expand it.

It would be interesting to also have how to open and close it via code.

**Comment by gnysek** [comment]
My proposal is `show_debug_overlay(enabled [, minimized])`.

**Comment by Neverdusk** [comment]
I have the same request. I always run my game in debug mode because it's a nice, minimal overlay with information. The new version takes up way too much of the screen - both the window and the bar at the top of the screen. Having a separate function or a "minimized" argument as suggested above would be incredibly helpful.

As is, it's actually less convenient than the older version most of the time. And I've found myself simply keeping it disabled.

**Comment by gnysek** [comment]
This is in latest beta FYI.

**Comment by gnysek** [comment]
@iampremo `2023.8` introduced `show_debug_overlay(enable[, minimised, scale, alpha]);` so seems that this FR can be closed?
