### ISSUE TITLE
SDF Effects (Runtime)

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1211]
Adds the ability to apply some basic effects to SDF fonts at runtime

- Glow
- Outline
- Change Thickness
- Drop Shadow

**Comment by W1llth0t** [comment]
hmm but what about multithreading support?

**Comment by Sholner** [comment]
Inline is possible? Even in Shaders it is difficult to find this option for text.

**Comment by dev816** [comment]
when is the release
