### ISSUE TITLE
The screen that shows errors could use this update for fixing typos.

### ISSUE THREAD

**Issue by stephengivens** [YoYoGames/GameMaker-Feature-Requests#1234]
### Is your feature request related to a problem?

Yes i did something wrong again and when i did find the error in the gml code screen(The area below the workspace) it show activity at startup and error sometimes show up there. when this does happen 50 percent are fixed within a few seconds as typos by comparing and sometimes you need a fresh install as it has become unstable. if the instability is in the piece of inherited software installed from another corporation like the piece that auto writes the possible thing you are typing and the search system for that has to have something to narrow it down. so this process might be leaving bits out like a memory leak but deleting them but leaving something. anyway if you make the error message from the white splash screen so that it will locate on clicking into the area of the error then all game maker error will be just the instability and not typo's in code. I believe they will vanish forever. please just try it. i repaired everything that ever showed up with a click just by comparing with the tutorial and my coding i did take two days once to see the actual error as they look the same and so highlighting  the exact area would then further reduce it too. then the message you would get is!!!( i need to replace the ram on my motherboard as it is unstable and causing bit errors. a very common issue in development. i hope this finds you all well. oh by the way i did screw it up again and can't find it yet so it is searching for misspelling again.

### Describe the solution you'd like

ok sorry looks like i am not used to this yet so a synopsys.!!! the white splash screen be activate to connect to the code and show like the area below the workspace. double clicking here will take you to the area that is claiming to be in error. i have found only typos and i am sure this feature along with a highlighting of the exact area would end 99 percent of all errors. the rest would be ram that lose bits and cause errors in save files on cheap computers.

### Describe alternatives you've considered

searching line by line is the only alternative and i have to use it right now. 

### Additional context

The region of the output area allow clicking to the location of the error but not all errors go to the this output area and so error that can't be fixed instantly exist. please allow the window that shows error to lead with a click back to the area of the mistake and highlight it and compare showing misspellings or omissions. [](url)
[This area does not show the same information as the output that leads to from under the workspace and does not click to the are in code and as it is not in gml.docx](https://github.com/YoYoGames/GameMaker-Feature-Requests/files/12254208/This.area.does.not.show.the.same.information.as.the.output.that.leads.to.from.under.the.workspace.and.does.not.click.to.the.are.in.code.and.as.it.is.not.in.gml.docx)

**Comment by stephengivens** [comment]
In these two places it shows the error i just caused and in some cases clicking in the output area you are taken to the code and the exact area of the error. i would like it to be clickable everywhere for finding the area for aiding in memorizing code. also the system in place lists Gml code when it list the area and not gmal visual. this remove my ability to find the place in the gml visual code. so could we have it clickable to file area location. This would be for file review and repair. it would be very useful for teacher to make explanations.. 
Teacher could cause and error then go to and click the error and it would go directly to it and then common errors could be fixed.I hope, i did this right this time. thank you for listening.
    On Friday, August 4, 2023 at 01:49:15 AM PDT, jackerley ***@***.***> wrote:  
 
 


Closed #1234 as completed.

**Comment by tabularelf** [comment]
I haven’t used visual, but I feel like most of your problems would go away if you used the debugger (F6)

**Comment by stephengivens** [comment]
I'm sorry i am really new and i ask a lot of questions to make sure i am doing it right and then i just typo like crazy. but i haven't made it to the manual yet. please don't get angry for some reason people do. it isn't free right but all i asked for was the curriculum and that people pay for so i am banned and just figured it out. i need to use f6 to use the debugger but that is what i asked them for. i told them how to get rich super easy to be friendly. look please don't get angry the kkk here in america make laws to make sure people don't do stuff. to prove it. i will teach you how to win any lotto. wait till a lotto resets the numbers then get the old list and probability will say that an exact same number will come up again within how many number 300. it is 90000 dollars to win three dollar per draw for 300 draws and you should win. in california they made a law saying it was unfair when i created this idea years ago. sorry but they run stuff here!!! anyway go look up debugger so fair trade. thanks can you give me anything about debugger. here is mine an object library in game maker with to many pieces can be used to make any game instantly for an artist this game will sell with an unlockable feature that cost money they replace and rely out. 10 genre 1 billion people is 750 billion dollars. that is a really large market. I only want 1 billion. sorry i went to school for marketing so it is just what i know how to do. good luck.    On Monday, August 7, 2023 at 11:23:16 PM PDT, TabularElf ***@***.***> wrote:  
 
 


I haven’t used visual, but I feel like most of your problems would go away if you used the debugger (F6)

**Comment by stephengivens** [comment]
sorry been misspelling again i am going to edit it and resend

    On Tuesday, August 8, 2023 at 06:24:02 AM PDT, stephen givens ***@***.***> wrote:  
 
  
I'm sorry i am really new and i ask a lot of questions to make sure i am doing it right and then i just typo like crazy. but i haven't made it to the manual yet. please don't get angry for some reason people do. it isn't free right but all i asked for was the curriculum and that people pay for so i am banned and just figured it out. i need to use f6 to use the debugger but that is what i asked them for. i told them how to get rich super easy to be friendly. look please don't get angry the kkk here in america make laws to make sure people don't do stuff. to prove it. i will teach you how to win any lotto. wait till a lotto resets the numbers then get the old list and probability will say that an exact same number will come up again within how many number 300. it is 90000 dollars to win three dollar per draw for 300 draws and you should win. in california they made a law saying it was unfair when i created this idea years ago. sorry but they run stuff here!!! anyway go look up debugger so fair trade. thanks can you give me anything about debugger. here is mine an object library in game maker with to many pieces can be used to make any game instantly for an artist this game will sell with an unlockable feature that cost money they replace and rely out. 10 genre 1 billion people is 750 billion dollars. that is a really large market. I only want 1 billion. sorry i went to school for marketing so it is just what i know how to do. good luck.    On Monday, August 7, 2023 at 11:23:16 PM PDT, TabularElf ***@***.***> wrote:  
 
 


I haven’t used visual, but I feel like most of your problems would go away if you used the debugger (F6)

**Comment by stephengivens** [comment]
i don't know why i wrote (rely out.) also the lotto has a typo it is 30 people in a family 10 tickets apiece. the old list if using exact same machine but new. 300 dollar total per draw for 300 should produce the winning tickets but was made illegal. only in california.    On Tuesday, August 8, 2023 at 06:29:34 AM PDT, stephen givens ***@***.***> wrote:  
 
  sorry been misspelling again i am going to edit it and resend

    On Tuesday, August 8, 2023 at 06:24:02 AM PDT, stephen givens ***@***.***> wrote:  
 
  
I'm sorry i am really new and i ask a lot of questions to make sure i am doing it right and then i just typo like crazy. but i haven't made it to the manual yet. please don't get angry for some reason people do. it isn't free right but all i asked for was the curriculum and that people pay for so i am banned and just figured it out. i need to use f6 to use the debugger but that is what i asked them for. i told them how to get rich super easy to be friendly. look please don't get angry the kkk here in america make laws to make sure people don't do stuff. to prove it. i will teach you how to win any lotto. wait till a lotto resets the numbers then get the old list and probability will say that an exact same number will come up again within how many number 300. it is 90000 dollars to win three dollar per draw for 300 draws and you should win. in california they made a law saying it was unfair when i created this idea years ago. sorry but they run stuff here!!! anyway go look up debugger so fair trade. thanks can you give me anything about debugger. here is mine an object library in game maker with to many pieces can be used to make any game instantly for an artist this game will sell with an unlockable feature that cost money they replace and rely out. 10 genre 1 billion people is 750 billion dollars. that is a really large market. I only want 1 billion. sorry i went to school for marketing so it is just what i know how to do. good luck.    On Monday, August 7, 2023 at 11:23:16 PM PDT, TabularElf ***@***.***> wrote:  
 
 


I haven’t used visual, but I feel like most of your problems would go away if you used the debugger (F6)
