### ISSUE TITLE
test fr

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#1259]
### Is your feature request related to a problem?

test

### Describe the solution you'd like

test

**Comment by tabularelf** [comment]
Great testing

**Comment by DragoniteSpam** [comment]
i think this is a feature request to name the gamemaker ai "glados" actually

**Comment by Totobal5** [comment]
i dont think game maker will use this one...

**Comment by KormexGameMaker** [comment]
Amazing request, please add this, it will make gamemaker the best engine in the world all on it's own!

**Comment by iampremo** [comment]
done
