### ISSUE TITLE
Room editor and sequence editor. During editing, call the Draw and Draw GUI event.

### ISSUE THREAD

**Issue by megalanthus** [YoYoGames/GameMaker-Feature-Requests#1284]
### Is your feature request related to a problem?

In edit mode, not all objects look like they look in runtime.

### Describe the solution you'd like

Room Editor and Sequence Editor. During editing, execute the draw and draw gui (and possibly create) event for the editor mode. This will make text, icons, and other objects that are drawn on top of the sprite visible. In other words, in editor mode, objects will look like they look in runtime.

### Describe alternatives you've considered

Alternatively, you could make a draw_in_edit_mode event that would only be called in edit mode.

**Comment by AtlaStar** [comment]
Great idea on paper, terrible idea in executing it.

Problems arise from the fact that a draw event might be dependent on variables defined in other events, or even other objects. This means that the draw behavior would need to have strict rules on how and when to render based on that event, and what to do if a code error occurs. Not only that but what if the asset is dynamically loaded and set in a create event? Do you try and load the resource, how do you signal errors if there was a failure to load the thing, etc.

I think the best alternative we can get is if instances in a sequence had the option to add a custom draw event where any code _has_ to be defined within that event, with the option to import the existing code and have it show errors if accessing properties not defined in that event. Anything outside of that is basically requiring that the sequence editor be the full Gamemaker VM with special error handling and guessing what users want if there would be an error (like not rendering the instance, which sounds like it'd confuse people more than help)

**Comment by megalanthus** [comment]
Ok, but what if we draw its tag over the object in the editor? Imagine a main menu with buttons: Play, Leaders, Settings, About the game. Seeing 4 identical rectangles is very painful.

**Comment by jackerley** [comment]
We are planning changes to the Room Editor, but we won't be going down exactly this track
