### ISSUE TITLE
Please make an isometric tile editor

### ISSUE THREAD

**Issue by Bottletaste125** [YoYoGames/GameMaker-Feature-Requests#1330]
### Is your feature request related to a problem?

Crying like crazy because there's no isometric tile editor.

### Describe the solution you'd like

Add ISOMETRIC TILE EDITOR and I'll be happy.
I'm so happy if you do that, I'll somersault.
해줘!!!!!!!!
I'll hold my breath until I get a positive answer Leave a positive answer if you don't want to be a killer!

**Comment by rosebrt** [comment]
This would require some pretty big leaps in the current tile editor system but would be suuuper nice to have, especially given that GameMaker is the primary engine choice _specifically_ for 2D-pixel art games, and to prospective dev deciding which engine to chose this feels like the kind of feature one might assume GM already has.

**Comment by YYDan** [comment]
Duplicate of #1389 - Closing.
