### ISSUE TITLE
Update live wallpaper template project

### ISSUE THREAD

**Issue by patrickrocheyoyo** [YoYoGames/GameMaker-Feature-Requests#1334]
### Is your feature request related to a problem?

the default live wallpaper template project should be updated to be the version that was edited by content interns. 

### Describe the solution you'd like

https://marketplace.gamemaker.io/publishers/tools/assets/11831 

Can we make the default live wallpaper template project the above version please?

**Comment by mgeddesGM** [comment]
[d58a49e130af8c879ea1b11a75f80dca.zip](https://github.com/YoYoGames/GameMaker-Feature-Requests/files/12927628/d58a49e130af8c879ea1b11a75f80dca.zip)
changes were made to the object code

verified as of  IDE v2023.1100.0.410  Runtime v2023.1100.0.433
