### ISSUE TITLE
Update OpenSSL

### ISSUE THREAD

**Issue by adam-coster** [YoYoGames/GameMaker-Feature-Requests#1349]
### Is your feature request related to a problem?

Our publisher runs security scans on our builds, and informed us of the following security issue **on Android**:

> The App embeds an outdated version of OpenSSL, which may be vulnerable to security issues:
yoyo.so--1.0.2f or earlier

Which, if I'm understanding correctly, means that the OpenSSL version shipped on Android is from 2015 or earlier.

I'm assuming that OpenSSL is used to mediate HTTPS and other secure connections, so having a more recent version would be good for security!

### Describe the solution you'd like

Have OpenSSL bumped to 3.0.0 (2021 LTS) or 3.1.0 (2023 LTS)

### Describe alternatives you've considered

I'm not actually sure how OpenSSL ends up in the build, so it could be something that we could resolve ourselves or that doesn't actually matter. I'm not sure how to figure that out!

**Comment by stuckie** [comment]
We use LibreSSL on version 3.5.3 - can you give us more details as to what extensions ( if any ) are building as to where OpenSSL may be coming from?

**Comment by adam-coster** [comment]
Gotcha, thanks for that info. Knowing that it's coming from an extension is probably all I need to figure out the rest of this!

**Comment by rwkay** [comment]
Please let us know what it was coming from... I am curious... you can contact us privately if you dont want everyone knowing.

**Comment by adam-coster** [comment]
@rwkay will do! Shi's out on leave so it might be a while before I have the answers
