### ISSUE TITLE
Resolve Zipperdown vulnerability

### ISSUE THREAD

**Issue by adam-coster** [YoYoGames/GameMaker-Feature-Requests#1350]
### Is your feature request related to a problem?

Our publisher runs security checks on our mobile builds, and reported to us the following vulnerability:

> **App Leverages Zip API Vulnerable to Zipperdown**
> The following Java or Kotlin classes within the App unzip archives in an insecure manner and might be vulnerable to the ZipperDown vulnerability:
> `com.yoyogames.runner.RunnerJNILib`
> `REDACTED.RunnerActivity`
> `REDACTED.IniBundle`

### Describe the solution you'd like

I'm honestly not sure what the risks are to us and our players of this vulnerability -- I'd like it to be resolved if possible, or otherwise get guidance on the kinds of risks it creates.

**Comment by stuckie** [comment]
This is to ensure we are not unzipping outside our current directory in a relative manner.
IE: ../some.file

**Comment by rwkay** [comment]
See https://wiki.sei.cmu.edu/confluence/display/java/IDS04-J.+Safely+extract+files+from+ZipInputStream for examples on compliant usage

**Comment by adam-coster** [comment]
Gotcha, so it sounds like GameMaker's usage of ZipInputStream accounts for those vulnerabilities?

**Comment by rwkay** [comment]
Errr.. we are not sure.. someone still needs to go and check to see if we are compliant - we were just trying to work out what the ZipperDown vulnerability actually was and get some more info about it... It seems to be mentioned a lot, but not a lot of information about what it actually does and how to avoid it.

So the discussion above was just us researching it.

We will assign it in the morning Triage I think.
