### ISSUE TITLE
Add a way to disable saving to local appdata if you try to save in the game directory

### ISSUE THREAD

**Issue by traumatizedgeworth** [YoYoGames/GameMaker-Feature-Requests#1372]
### Is your feature request related to a problem?

This saving prevention has been an issue for me with numerous projects I've done when trying to make a save/load system that works with files people can save and load anywhere

### Describe the solution you'd like

Even if it's tucked away at the bottom of some small area in the game settings, with 50 warnings on it, there should be a small checkbox to disable the forced local appdata saving

### Describe alternatives you've considered

The only alternative I've come across is putting a text file with the game that tells you not to save in the game directory, but that's very clunky

### Additional context

I don't care about "corrupting game files," I'm using a custom file format anyway so that would never happen unless there was someone deliberately trying to corrupt their own game files on purpose. I feel like situations like these should be taken into account

**Comment by tabularelf** [comment]
I think something to add here, specifically for desktop. Mobile/Web/Consoles have all kinds of restrictions so we can't actually do anything about them there.

But in desktop apps, even including Windows, you can write to the program directory. The only main concern I've heard in regards to Windows is that if your game is in Program Files, then you need to evaluate it to admin privileges (as you usually can't really write to Program Files without it)

**Comment by rwkay** [comment]
If you have the file sandbox disabled then GameMaker is not doing anything to your file writes... Windows itself does not allow non-admin accounts to write to Program Files so there is nothing that we can do in that case.

**Comment by tabularelf** [comment]
I think the issue might be that disabling file sandbox is intended to allow to writing to the program directory, but perhaps there's some kind of bug? Because even if I use `program_directory` to specify the exact program location, and save a small text file, it saves it straight to the "safe" game save directory. Even if this is in a place where the user would have the rights to run it. Such as desktop, where one *can* in fact save with multiple different kinds of programs then.

I was actually just testing this just now, with file sandbox disabled. And it's writing to the "safe" game save directory.
```gml
var _buff = buffer_create(1, buffer_grow, 1);
buffer_write(_buff, buffer_text, "Hello world!");
show_message(program_directory + "hello.txt");
buffer_save(_buff, program_directory + "hello.txt");
buffer_delete(_buff);
```

**Comment by tabularelf** [comment]
Even if I escalate it to admin privileges, it *still* writes to the "safe" game save directory.

**Comment by rwkay** [comment]
file a bug... there may be an issue where the program_directory is getting rewritten to be the save area before the sandbox restrictions are checked.... that would be a bug..  attach the project to it.

**Comment by tabularelf** [comment]
@rwkay Done! [#1885](https://github.com/YoYoGames/GameMaker-Bugs/issues/1885)

**Comment by traumatizedgeworth** [comment]
![image_2023-10-10_172020196](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/127890905/51ca1fc7-7f42-4604-8d0b-2e45cdea7656)
i don't think it's a bug, this is in the docs (image is from judacraz on discord)

**Comment by tabularelf** [comment]
Sometimes things can change and won't be reflected on the manuals end.
Source: I had this problem with `script_execute_ext`.
