### ISSUE TITLE
Game Maker 2 for Linux

### ISSUE THREAD

**Issue by xaropizao** [YoYoGames/GameMaker-Feature-Requests#1374]
### Is your feature request related to a problem?

I use Game Maker 2 a lot to develop my game ideas, but the fact that it can only be used on Windows or Mac makes my process difficult, as my entire ecosystem is on Linux, I use Linux on my desktop and on my notebook. Whenever I need to use Game Maker 2, I have to turn off my PC and dual boot Windows.

### Describe the solution you'd like

It would basically be Game Maker 2 but compiled for Linux systems such as Arch, Ubuntu...

**Comment by iampremo** [comment]
Ubuntu IDE is available in beta, you can get the link to the lastest one from to top of this page https://gms.yoyogames.com/ReleaseNotes-NuBeta.html

**Comment by Shadowblitz16** [comment]
> Ubuntu IDE is available in beta, you can get the link to the lastest one from to top of this page https://gms.yoyogames.com/ReleaseNotes-NuBeta.html

It's been in beta for the past 4 years.



> ### Is your feature request related to a problem?
> 
> I use Game Maker 2 a lot to develop my game ideas, but the fact that it can only be used on Windows or Mac makes my process difficult, as my entire ecosystem is on Linux, I use Linux on my desktop and on my notebook. Whenever I need to use Game Maker 2, I have to turn off my PC and dual boot Windows.
> ### Describe the solution you'd like
> 
> It would basically be Game Maker 2 but compiled for Linux systems such as Arch, Ubuntu...
> ### Describe alternatives you've considered
> 
> _No response_
> ### Additional context
> 
> _No response_

Don't count on it.
I'm a linux user too, but yoyo games don't care.

Linux support isn't even in their roadmap.
