### ISSUE TITLE
In-Game: Add a new timing method that allows the game time to be controlled by the device

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Feature-Requests#1450]
### Is your feature request related to a problem?

Yes, it was related to issues found investigating frame rate problems trying to run at 120Hz on some specific Android devices:

[OnePlus 9 Pro](https://github.com/YoYoGames/GameMaker/issues/2554) 
[Samsung Galaxy Fold 4](https://github.com/YoYoGames/GameMaker/issues/2553) 

We should have a cross-platform system which will remove all our sleeps and gamespeed control and allow the game speed to be set by the system, which will allow the devices to then handle the game as they wish,

### Describe the solution you'd like

Add a new timing method, which can be used on all platforms.

Do this via adding a new timing method constant "tm_systemtiming", to be used with the existing display_set_timing_method(). E,g,:

`display_set_timing_method(tm_systemtiming);`

**Comment by YYDan** [comment]
Is already in Nov23 Betas and can be tested using this sample: [testAndroidFPSLock-2.zip](https://github.com/YoYoGames/GameMaker-Feature-Requests/files/13307776/testAndroidFPSLock-2.zip)

**Comment by KamilWdowczyk** [comment]
@YYDan Is it also for iOS? I have this issue with iPad Pro

**Comment by YYDan** [comment]
No, iOS uses ProMotion already and does not have this issue.

This is purely for Android, as it says in the Description (however, I will go reword the title now to make that clearer).

**Comment by YYDan** [comment]
Hehe, correction - I have now been given updated info that this _should_ work on all platforms, so editing the title again...

@KamilWdowczyk Have you tried your iPad issue in the November betas? It's possible your issue is the current known issue with ProMotion and 120hz-capable devices, for which a separate fix has gone in already. You will likely find you don't need this change anyway on iOS, but "yes, it should work".

**Comment by YYDan** [comment]
The manual change is fine/correct, as it clarifies that specific Android devices may require this, but does _not_ say that only Android supports it.
