### ISSUE TITLE
Add SyncF5 Function for Live Wallpaper Save buffers

### ISSUE THREAD

**Issue by patrickrocheyoyo** [YoYoGames/GameMaker-Feature-Requests#1451]
### Is your feature request related to a problem?

Add SyncF5 Function for Live Wallpaper Save buffers. This would allow gamestrips and live wallpapers to communicate more frequently.

### Describe the solution you'd like

Add SyncF5 Function for Live Wallpaper Save buffers

### Additional context

Added at request of @rwkay - required for content team work

**Comment by rwkay** [comment]
OK checking the code and it would appear that any file save (like buffer_save()) will do an FS.sync in the background.

**Comment by rwkay** [comment]
Added in 2023.11 - new function `gxc_file_sync( [callback] )` does a full file sync and calls an optional GML callback function when done.
