### ISSUE TITLE
Static functions should have non anonymous names

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Feature-Requests#1469]
### Is your feature request related to a problem?

`static Add = function(a,b) { ... }` has an anonymous name, when the declaration style implies this would be an unchanging function, so it wouldnt need an anonymous name.

currently the only way to get a readable function name inside a constructor would be to do the following
`function Add(a,b) { ... }`

Examples:
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/14dd424f-23c6-4134-bb1a-6aad1196bc74)
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/9a237de9-c9d6-4b2a-827f-31d2bdaa7d8c)
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/ed4fca7e-98e1-43e4-8cca-f6be1f1a9e24)

### Describe the solution you'd like

`bar` in the example above should have a name similar to `gml_Script_bar_myConstruct_gml_GlobalScript_Script3`

### Describe alternatives you've considered

ability to manually name a function would be nice, help a **lot** for debugging purposes.

Currently i actively use the following to do so:
```
static Add = function Add(a,b) { ... }
```
Which isnt ideal as this also produces a local variable inside the first creation of the instance, but it does give me a usable name to read when debugging. Small price to pay.

### Additional context

![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/0eece75c-6f37-4e32-9458-2f0b506e2592)

**Comment by AtlaStar** [comment]
The _only_ thing I sort of dislike is that if you try and enumerate all the functions and then filter out anon's, such a change would then make it to where methods of a struct are included in those results. As such I do think that _some_ sort of identifier should be added to the naming so that it both doesn't have as messy of a name, but also shows that it is a static function of some struct and not something that is usable as a global function.

So perhaps something as simple as replacing the `_anon_blahblahblah` junk with `static_bar` if using your example to get the desired name, or maybe even some other token that is a prefix to `bar` or the entire function name that denotes that it was declared as a static of something.

**Comment by tinkerer-red** [comment]
@AtlaStar This concern is easily rectified by the fact that the function name will be prefixed by the outer function name, in your example this would be a constructor. you can see this in the supplied example where `myConstruct` is included in the function name.
Additionally this is already how using `function bar(){}` already generates names, So your concern still arises in current gml. If you could give further use case for such code that may be insightful, as I am confused when one would want to differentiate anon functions from any other functions. Maybe global from methods, but i see no difference between `foo` and `bar` in `myConstruct`

**Comment by rwkay** [comment]
I am thinking of making the anonymous function name include the name that it is going to be assigned to as a static so for example `static bar = function() { }` then the anonymous function would be called something like `bar@anon48@myConstruct`, this should allow users to track functions better

**Comment by AtlaStar** [comment]
> @AtlaStar This concern is easily rectified by the fact that the function name will be prefixed by the outer function name, in your example this would be a constructor. you can see this in the supplied example where `myConstruct` is included in the function name. Additionally this is already how using `function bar(){}` already generates names, So your concern still arises in current gml. If you could give further use case for such code that may be insightful, as I am confused when one would want to differentiate anon functions from any other functions. Maybe global from methods, but i see no difference between `foo` and `bar` in `myConstruct`

This is mostly a concern of using something like the new function `asset_get_ids(asset_script)`, which returns _all the functions in the game_. So with the returned array, you have no way to differentiate if the function was a global one or not without having to first parse the functions that were returned, but then run into issues of having to test for a _lot_ of different cases depending on the declarative scope to determine whether it is an anon, an anon that was bound to a static, or a function declaration that was enclosed in the scope of something other than a script asset.

I personally think that a system like Russell has described should be applied to every function, where the ampersand represents a scope context such that `function foo(){}` in your example generates `foo@MyConstruct@Script3@GlobalScript`, bar generates `bar@static##@MyConstruct@Script3@GlobalScript` and a anon not bound to static generates something like `anon##@MyConstruct@Script3@GlobalScript` for example.

**Comment by tinkerer-red** [comment]
Ah I have not been on Beta to try `asset_get_ids` yet. Didn't know that's how it worked, but makes sense for the concern. Though I do like this approach of a hierarchal naming convention to include static as a parent. really like this solution `bar@static##@MyConstruct@Script3@GlobalScript` though it is a bit noisy to read, but thats a minimal issue.

**Comment by AtlaStar** [comment]
It is noisy, but it is easily split-able such that you can generate an array with all parts of the function "path" quite easily, which might have use to someone /shrug

**Comment by tinkerer-red** [comment]
would just personally favor some other delimiter. `/` `|` `.` etc

**Comment by rwkay** [comment]
Fixed in 2024.2 - see my comment above on how it is named.
