### ISSUE TITLE
Runtime access to object variable definitions

### ISSUE THREAD

**Issue by zzhamzz** [YoYoGames/GameMaker-Feature-Requests#1481]
### Is your feature request related to a problem?

A few cases where this would help one example being:

I want some 'game-wide' settings variables (i.e. globals). Currently the solution would be:

1. make them globals in code
2. make them macros in code if applicable
3. make them instance variables and make sure the instance exist. Either in code or via object variable definitions.
4. make some sort of singleton pattern in code

The above may be done with hardcoded values or read from a file etc..

I would like a solution using the current object variable definition interface.  However, there is no current language access to object definitions without at least instantiating the object; essentially doing the third option above.

### Describe the solution you'd like

Add additional variable_* like functions for reading object variable definitions.
 
e..g.

variable_object_exist
variable_object_get_names
variable_object_get

etc..

Read only is fine, read and write would be better.  These would read the variable values without having to instantiate the object.

Addtionally it would be amazing to be able to read these variable on non-instantiated instances; i.e. instances manually placed on a room layer, but the room is not yet loaded.

e.g.

- Object X has variable definitions
- We place an instance of object X in a room
- We override one or more varibale definitions for the specific instance
- Without entering the room we access the instance (via layer_set_target_room and layer_instance_get_instance) and read those varibale definitions.

With the above it could still use variable_object_* functions that accept either an object id or and instance id.  This way we could still distinguish between the instantiated value of an instance variable and its default value set in object definitions; 

- variable_object_* (passed object index) reads from object variable definitons
- variable_object_* (passed instance id) reads from instance variable definitions 
- variable_instance_* read the variables from the runtime instance

The above suggestion would increase the capability of rooms being used as 'data' without being entered.

### Describe alternatives you've considered

Consider adding 'data containers' that can be created/manipulated in the asset tree UI, can be placed/manipuled on asset layers, and accessible at runtime without loading a room or 'instantiating' anything.

Essentially that is what I am asking for but incorporating the existing object variable definitions features.

**Comment by yoshikins** [comment]
Please please please!

So currently all variable definitions for objects and room instances are converted into code. It's called the precreate event and can even be called with event_perform. The values themselves arent stored or serialized with any other method so I think being able to get them individually at runtime would not be possible, unless yyg made a lot of changes internally to how these get stored and serialized. 

I remember I would perform a similar thing by dispatching object events into empty structs and then treat those structs as the static object variable data, however this was undefined behavior and was understandably patched out some time ago.

Now my current solution to this sort of stuff involves caching instance structs, while deleting the instance itself, which I still feel is borderline undefined behavior. 

I would absolutely love to see like an IDE plugin or some new type of asset that basically had this exact purpose. Just a static data container that can be edited from within the IDE itself and referenced in code, the room editor, or heck even sequences maybe. It could reuse the interface from the object variable definitions tab, and may even see more IDE functionality than what we have right now.

This is speculation but the introduction of prefabs may even bring something like this closer to fruition.

I think this is an amazing idea and I want yyg to see this, and at the very least hear some input on it. Although I would rename this feature request to highlight the alternative solution as I genuinely feel that's the best way to go in this case.

**Comment by zzhamzz** [comment]
> unless yyg made a lot of changes internally

Undoubtedly they would have to change how these are stored and invoked.    My suggest for implementing it within how things currently work.

Consider how the functions instance_create_layer/depth function can accept a struct to use for variable initialization

- Every object in the asset tree has a corresponding struct that holds the variable definiitons
- Every instance manually placed on a layer is associated with with a struct that holds the variable definitions
- These structs are used in the precreate event
- The requested variable_object_* functions access and manipulate those structs

**Comment by yoshikins** [comment]
As of right now and historically, the variable defintions are converted into an event at compile time, you can even call the event with event_perform, this includes both object assets and room instances now thanks to room_get_info(). I doubt yyg would make a change that large to how they're processed and stored in order to implement these features. Assuming that they're all stored as structs because of the optional struct you can pass into the create functions, is a bad assumption to make.

My suggestion was to use your alternative solution, as it seems it's the most realistic option that yyg would consider as I doubt as many changes would have to be made internally in order to get it functioning, although that itself is an assumption.

**Comment by zzhamzz** [comment]
> Assuming that they're all stored as structs because of the optional struct you can pass into the create functions, is a bad assumption to make.

There are no assumptions being made. Only suggestions.

**Comment by yoshikins** [comment]
That's fair then. Honestly I guess I fail to see the application of this then, given that we basically already have access to everything we need to get these values at runtime.

**Comment by zzhamzz** [comment]
> already have access to everything we need to get these values at runtime.

There is no explicit runtime access to Variable definitions.  The only possible access is instantiating an instance or running the pre-create event.   Both of which have side effects(documented or otherwise) in order to just access data.  The newer room_get_info function provides access to the pre-create function of an instance in a room, not the actual variable definitions.

AFAIK there is almost no documentation of the 'pre-create' event.  

The general application is to be able to access data without modifying unrelated state.

IMO: the biggest hurdle for this suggestion is the fact that the values of variable definitions are clear as code (at execution time), and ambigious as data.

e.g. 'expressions' can be entered as variable definitions values.  In general expressions cannot be serialized.  This is the primary implementation hurdle.  I put 'expressions' in quotes as currenlty every value in variable definitions is 'executed' as code, essentially making all variable definitions are 'expressions.'

**Comment by zzhamzz** [comment]
After this discussion I think I agree that the current Object Variable Definition probably isn't the best canidate to refactor into what I suggest.

Thanks for the convo.
