### ISSUE TITLE
Static variable access shorthand for functions & constructors using member & struct accessors

### ISSUE THREAD

**Issue by coyo-t** [YoYoGames/GameMaker-Feature-Requests#1493]
### Is your feature request related to a problem?

Currently you access static variables stored in constructors & functions via `static_get(func).some_static` or `static_get(func)[$ "some static"]`.
This is a fine feature, far more than other languages allow. However, it is also a little clunky and long winded. There are some interesting techniques that could be done that aren't seen in other languages if it could be shorthanded.

### Describe the solution you'd like

`static_get(func_or_constructor).something` should be shortenable to just `func_or_constructor.something`, as well as `static_get(func_or_constructor)[$ "some thing"]` to `func_or_constructor[$ "some thing"]`.

Probably would be compiled back to `static_get(x).y`.

### Describe alternatives you've considered

There isn't really a clean solution to this natively, short of writing a macro like `#macro CLS_STAT (static_get(SomeClassOrFunctionFrequentlyUsed))`/shoving it into a globalvar. Which you would have to do for every frequently used static struct. Which just pollutes the global namespace.

### Additional context

The obvious use case for this is emulating static class variables & methods (although, true static methods aren't possible in GM as it stands). The more interesting use that no other language I know of lets you do however, are with static method/function variables. Example: you have your own buffer constructor for whatever reason, and it has a `seek` method like such:
```gml
static seek = function (offset, origin)
{
	static OFFSET = 0;
	static START = 1;
	static END = 2;
	
	switch (origin)
	{
		case OFFSET: ...; break;
		case START:  ...; break;
		case END:    ...; break;
	}
}
```

With static member access shorthand, a user can do:
```gml
var f = MyBuffer(...);

f.seek(292202, f.seek.OFFSET);
```
rather than having to have their constants be defined with a global companion enum/macro

**Comment by rwkay** [comment]
if you name the function you can already do this i.e.

```
function Foo() {
  static bar = 20;
}

show_debug_message( $"Foo.bar is {Foo.bar}" );
```

The compiler needs to be able to fully resolve the name of the function though so the function needs to be at global scope.

**Comment by coyo-t** [comment]
> if you name the function you can already do this i.e.
> 
> ```
> function Foo() {
>   static bar = 20;
> }
> 
> show_debug_message( $"Foo.bar is {Foo.bar}" );
> ```
> 
> The compiler needs to be able to fully resolve the name of the function though so the function needs to be at global scope.

I Can't test fully because login problems (doesn't apply your user preferences unless you restart, but i keep getting logged on restart??) but
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/22027276/2a2bf091-9c26-4acc-bed5-bc4105c591f8)
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/22027276/c95976c0-c6f3-4b49-a6c1-42db07972667)
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/22027276/9dd3c6f2-cb78-431c-a66b-b8d298d70abc)
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/22027276/16bc9e04-7912-436c-84a1-6a7ed5b6a999)

:/

**Comment by rwkay** [comment]
what version are you on?

**Comment by coyo-t** [comment]
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/22027276/77c5dc5a-12f7-45bf-95aa-85ba6752d632)
Yeah the TOS accept fixed the login issue

I already knew about the above problem with accessing static variables though, aside from it working if the function has been used at least once (which makes it practically unusable for things like my above seek example or storing static instances/inheritors of a struct inside itself v_v). I think it working at all is new, I don't remember being able to do it under any circumstance in the past.

**Comment by rwkay** [comment]
Actually I am being stupid you need to have called the function at least once so the statics are assigned - they are assigned on the first call so in my example you need to do...

```
function Foo()
{
	static bar = 20;
}
Foo();

show_debug_message( $"Foo.bar is {Foo.bar}" );
```

In yours you would have to do 

```
function seek()
{
	static START = "start";
	static END = "end";
	static OFFSET = "offset";
}

seek();

show_debug_message($"seek.START = {seek.START}" );
show_debug_message($"seek.END = {seek.END}" );
show_debug_message($"seek.OFFSET = {seek.OFFSET}" );
``

I have checked this on 2023.11 Beta and it works... it should work since 2023.1 (when this syntax was introduced).

**Comment by rwkay** [comment]
Not sure I agree with your practically unusable as I personally find it very easy to just put it into a script asset and then call the function within that script assets... you can then treat the script asset with multiple functions and declarations like a library the call happens at global scope before anything else starts so the user does not even have to call them themselves.

So you would have a `scr_Utils` script asset and that would contain some utility functions and definitions like so

```
function seek()
{
	static START = "start";
	static END = "end";
	static OFFSET = "offset";
}

seek();
```

Then in the rest of your code you would use it like

```
show_debug_message($"seek.START = {seek.START}" );
show_debug_message($"seek.END = {seek.END}" );
show_debug_message($"seek.OFFSET = {seek.OFFSET}" );
```

the `seek()` call is done at global initialisation before a room even starts.

**Comment by coyo-t** [comment]
> Not sure I agree with your practically unusable as I personally find it very easy to just put it into a script asset and then call the function within that script assets... you can then treat the script asset with multiple functions and declarations like a library the call happens at global scope before anything else starts so the user does not even have to call them themselves.
> 
> So you would have a `scr_Utils` script asset and that would contain some utility functions and definitions like so
> 
> ```
> function seek()
> {
> 	static START = "start";
> 	static END = "end";
> 	static OFFSET = "offset";
> }
> 
> seek();
> ```
> 
> Then in the rest of your code you would use it like
> 
> ```
> show_debug_message($"seek.START = {seek.START}" );
> show_debug_message($"seek.END = {seek.END}" );
> show_debug_message($"seek.OFFSET = {seek.OFFSET}" );
> ```
> 
> the `seek()` call is done at global initialisation before a room even starts.

The seek func being at global was just for testing, I don't think it would work with smth like this
```gml
function Buffer () constructor begin
	static seek = function (offset, origin)
	{
		static OFFSET = 0;
		static START = 1;
		static END = 2;
		
		switch (origin)
		{
			case OFFSET: ...; break;
			case START:  ...; break;
			case END:    ...; break;
		}
	}
end


// wont work
show_debug_message(Buffer.seek.OFFSET);

var f = new Buffer();

// probably wont work?
show_debug_message(Buffer.seek.OFFSET);

// pretty sure this wouldnt either
f.seek(0, Buffer.seek.OFFSET);

```
Your example is odd and at that point you might as well just add a proper namespacing system to the language >_<
Or use globalvars (which is what I wound up doing for an earlier project for "Block Type" classes. Which was very annoying because you cant declare and assign to a globalvar at the same time).
```gml
globalvar things;
things = {
  //...
};
```

**Comment by tinkerer-red** [comment]
> proper namespacing system to the language >_<
global.namespace = {};
