### ISSUE TITLE
Multiple Tilesets for a single layer

### ISSUE THREAD

**Issue by hexaWASD** [YoYoGames/GameMaker-Feature-Requests#1517]
### Is your feature request related to a problem?

Having many large tilests and being able to use only 1 on a single layer is really frustrating, please add being able to use any amount of tilesets you want on a single layer.

### Describe the solution you'd like

Layers should let you pick which tileset you want and after using it being able to switch to a different one without losing the previous tiles you used.

**Comment by stuckie** [comment]
This is not currently planned.
The way the tile layers are currently set up is that they match up with a single tile map, and this would require a larger change to allow multiple tile maps per layer.
You will have to use multiple layers, and leave gaps in higher layers to show the tiles in the lower layers as required for now.

**Comment by nullbunny** [comment]
What if during the asset compile step, GameMaker created a tileset of all compatible tilesets and adjusted the tile indices? Like, combine all sets that have the same tile size and texture group. Could also remove duplicates and empty tiles in that step, too, like the sprite packer already does with duplicate frames.
