### ISSUE TITLE
room_get_info() - add more info in layer_elements of objects

### ISSUE THREAD

**Issue by dt-universe** [YoYoGames/GameMaker-Feature-Requests#1519]
### Is your feature request related to a problem?

Impossible to get scale of instance in room data.

### Describe the solution you'd like

Add info about scaling to instance info.

**Comment by rwkay** [comment]
within the instance data `xscale` and `yscale` are already provided

**Comment by dt-universe** [comment]
Hm, I found that when we get **layers** and **layer_elements** from room_get_info, in **layer_elements** instances data is useless, because it just consists id, type and inst_id. How we can from **layer_elements** get more data about instance, like from **instances** directly? I mean, we must have all this info (x, y, image_xscale, image_yscale, etc) about instances in **layer_elements** too.

For example, if we want to get positions of all objects on layer in a room, so we find this layer in struct **layers** and iterate though **layer_elements** array and search instance's info with inst_id in another array **instances**, but if we will have whole info right in **layer_elements**, we don't need to do this step.

![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/23583854/38b195b7-50e5-488b-a298-1b7143b77106)

**Comment by gurpreetsinghmatharoo** [comment]
Added xscale and yscale to the Instance Info table on room_get_info

**Comment by dt-universe** [comment]
May I ask, will you add more info about instances in layer_elements array or this issue completed just with docs?

**Comment by gurpreetsinghmatharoo** [comment]
Could you please open a separate issue for that, as this was for xscale/yscale missing from the docs and that is complete now.
