### ISSUE TITLE
Function to convert string of a handle into a handle

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Feature-Requests#1536]
### Is your feature request related to a problem?

Prior to 2023.11, one way to pass a surface around was through a string of it's ID, then back into a reference with the `real()` function. (e.g, in Juju's Scribble)

Now that surfaces are typed references, this option no longer works, and as best I can tell, there's no way to convert a string of a handle back into a handle.

### Describe the solution you'd like

add a function (e.g. `handle("ref surface 1")`) that can convert a string of a handle back into a handle 

### Describe alternatives you've considered

if it needs to be more complex, e.g. `handle_create(ref_type_surface, 1)` (which would then require parsing the handle string to extract the id integer) that would be fine with me. But any other alternative would mean refactoring for anyone that passes references like this, which is a bummer for solutions like Scribble that are centered around parsing strings to extract data. 

Specific to Scribble, Juju is currently talking about adding a `.bind_surface()` method to scribble as a workaround to attach/pass any surfaces that are needed in a scribble element.

**Comment by rwkay** [comment]
Added in 2024.2 - new function `handle( value_string )` takes a string and converts it into a handle - string is in the format of a handle that has been converted into a string (so currently that is `ref <type-of-ref> <number>`)
