### ISSUE TITLE
macOS Modern Gamepad Support

### ISSUE THREAD

**Issue by RykinPoe** [YoYoGames/GameMaker-Feature-Requests#1537]
### Is your feature request related to a problem?

Modern macOS on Apple Silicon no longer supports old gamepads like the Xbox 360 gamepad, but GameMaker only officially supports Xbox 360 and PS3 gamepads on macOS.

### Describe the solution you'd like

Add support for modern gamepads like the Xbox Series, PS4, PS5, Switch Pro, and other modern controllers to GameMaker for macOS. Many of these controller are now officially supported in macOS, iOS, and tvOS by Apple and many of them work great with GameMaker on Windows as well.

### Describe alternatives you've considered

I am unsure what alternative there is. I have tested a number of different controllers that I own (Xbox 360, Xbox One(launch version without Bluetooth), Xbox Series, and Switch Pro) on macOS Sonoma on an Apple Silicon based Macintosh. Many of them work great with macOS and games made with other development tools, but they do not work correctly in GameMaker projects.

### Additional context

Willing to help submit profile information on some of the controllers I have, but I am not sure what exactly you would need.

**Comment by YYDan** [comment]
For the most part (more on this below), we see these pads working just fine in our projects here; however, do be aware that for all of them the Mac itself needs to have an entry for the pad in System Settings > Game Controllers and they must be connected via Bluetooth. Some of those pads seem to install their drivers and set up the BT connection automatically if you connect them via USB (e.g., PS5) whereas others will require you to put the pad into pairing mode and detect them manually in the System Settings app (e.g., Series X).

Mac Silicon makes no difference, btw, as our Intel Macs which are stuck on Monterey are exactly the same results for every pad we tried.

Please check your Mac is detecting the pads okay and then compare your own project's gamepad code against the various examples in our manual/templates (e.g., Windy Woods once you're past the main menu screen) and I am sure you will get them working no problems.

However, where there IS an issue is that the Switch Pro pad does not work properly on macOS VM builds - the thumbstick is coming in as a D-pad and only moving right is reliable. All other buttons either do not work at all (e.g., all the face buttons and the actual D-pad), or they are inconsistent (e.g., moving left/up keeps requiring you to release and re-move the stick).

I will file a separate bug for that one, plus a docs bug to get the line in the manual updated.
