### ISSUE TITLE
"string_contains" function

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Feature-Requests#1545]
### Is your feature request related to a problem?

I want a nice and built-in way to check if a string contains another string.

### Describe the solution you'd like

A function `string_contains(str,substr)` which checks if the substring exists anywhere in the string, much like `string_starts_with` checks it for the start and `string_ends_with` checks it for the end.

### Describe alternatives you've considered

Using `string_pos(substr, str) > 0`, but same could be said about `array_contains` in relation to `array_get_index`.

**Comment by BackYard321** [comment]
I was just looking for this last week in the documentation! Definitely would make a ton of sense to have.

**Comment by jackerley** [comment]
I think if(string_count(str,substr)>0) will do exactly what you want?

**Comment by BackYard321** [comment]
> I think if(string_count(str,substr)>0) will do exactly what you want?

Alphish mentioned that this workaround exists, but it's inelegant and the equivalent exists for arrays - even though the option to do `array_get_index(_array, _value) > -1` exists, we also have `array_contains(_array, _value)` which is just generally preferable.
