### ISSUE TITLE
GM_project_filename should not be included in release executables

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Feature-Requests#1550]
### Is your feature request related to a problem?

It appears that the GM_project_filename constant is included even in release executables. As the constant is a filepath on the developer's personal machine, this is personally identifiable information that will end up baked into the executable distributed to any user! That's bad.

### Describe the solution you'd like

GM_project_filename should only be included when running a project from within the GameMaker IDE. In a packaged executable it should evaluate to either undefined or `""`

**Comment by rwkay** [comment]
If you do not want this output going to the final executable then ensure that it is optimised out using constants to ensure that the Conditional statement is constant i.e. using the `GM_build_type` compile time constant like this

```
#macro PROJECT_DIR (GM_build_type == "run" ? GM_project_filename : "")
```

then using the PROJECT_DIR macro instead of GM_project_filename
