### ISSUE TITLE
room_number() function

### ISSUE THREAD

**Issue by GimmeDatFreeSoftware** [YoYoGames/GameMaker-Feature-Requests#1586]
### Is your feature request related to a problem?

My request is related to a problem. I am making a roguelike where once you defeat all enemies you walk through a door and the door takes you to another room. My problem is that I want it to pick out a random room to go to using random_range(). I could change the second parameter every time I made a room, but that would be tedious.

### Describe the solution you'd like

A room_number() function would get the number of rooms, which I could use as the second parameter for random_range() so that it could teleport to a random room out of all of the rooms.

**Comment by Alphish** [comment]
For your specific use-case, I'd rather instead tag all the rooms (e.g. "dungeon_room") and then use [tag_get_asset_ids](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAssets_And_Tags%2Ftag_get_asset_ids.htm) to retrieve all the rooms the player can go to, like so:
```gml
var _available_rooms = tag_get_asset_ids("dungeon_room", asset_room);
var _target_room = script_execute_ext(choose, _available_rooms);
room_goto(_target_room);
```

This kind of system can be easily modified to be more flexible; e.g. use different tags for different areas, or add extra possible rooms as the player goes deeper etc. Plus, there's no chance of a stray main menu room and similar entering the list of possible rooms.

(another alternative is using `asset_get_ids(asset_room)` to get all the rooms in existence, and e.g. recognising valid target rooms by their names; the point is, a system based around tags or array of rooms will be overall more robust than random_range-choosing the room to go to)

Not saying that such a `room_number()` function would be useless. Rather, the proposed use case doesn't make for a good application, with it being rather inflexible and prone to errors (if compiler decided to put main menu room between dungeon rooms, for example).

**Comment by Gamer-XP** [comment]
We already go it:
https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Rooms/room_last.htm

In my case, I have some utility rooms in the beginning on the room list, then "loading" room at the end, and actual rooms going after it. If I'm to find a random room, I'd to it by irandom_range( rm_Loading + 1, room_last )

**Comment by jackerley** [comment]
As above
