### ISSUE TITLE
Need a way to prevent clicking through the new debug overlay.

### ISSUE THREAD

**Issue by jarrrodnb** [YoYoGames/GameMaker-Feature-Requests#1590]
### Is your feature request related to a problem?

As the developer of a game that makes extensive use of the mouse (targeting NPCs/objects etc.), it's very frustrating to use the debug overlay when I'm constantly selecting game objects/clicking GUI elements through it.

I've been able to hack together workarounds to prevent clicking anything while it's open but then I need to be constantly toggling it on/off to use it effectively.

### Describe the solution you'd like

I'm not looking for built-in support to prevent clicking through, but rather a simple function that returns a true/false if the cursor is anywhere over the debug overlay.

Eg.
`debug_overlay_get_mouseover`

**Comment by L-Clouds** [comment]
I had previously asked in one of the update release threads on the forum whether there was a way detect if a click was on an ImGui window, but didn't get any answers.  I guess there isn't!  Anyway, yes, very needed.

**Comment by rwkay** [comment]
Currently we do not have a reliable way to handle this (currently we cannot tell if the mouse is over an imgui window) but you can use the `is_debug_overlay_open`  API so you can decide if the mouse click should be used or not

**Comment by rwkay** [comment]
looks like we could add a function that allows users to tell if the mouse is over an imgui window - https://github.com/ocornut/imgui/issues/52

**Comment by shdwcat** [comment]
@rwkay couldn't GM use that to just not send the clicks to the runtime at all? It seems a hassle to make users have to know about and know how to handle this when the system can and should solve the problem

**Comment by rwkay** [comment]
I will take a look and see what can be done

**Comment by rwkay** [comment]
Feature added in 2024.2

* Mouse and Keyboard Events are no longer passed to the game if ImGui is using the mouse or the keyboard
added 2 new functions
* `is_mouse_over_debug_overlay` - Returns true if the mouse is over a debug overlay window or gadget, or is being used by the debug sub-systems (i.e. for dragging)
* `is_keyboard_used_debug_overlay` - Returns true if the keyboard is being used by the debug overlay system
marked those functions as Pure in GmlSpec.xml (also changed `is_debug_overlay_open` to be Pure
