### ISSUE TITLE
3d

### ISSUE THREAD

**Issue by Kyu321** [YoYoGames/GameMaker-Feature-Requests#1593]
### Is your feature request related to a problem?

Olá, eu comecei a um ano mais ou menos a programar no Gamemaker e acho que ela é a melhor e mais fácil de se entender, mas estou tentando implementar algo mais elaborado, como um pequeno Top Down 3d e mesmo com tutoriais diversos, achei muito complicado o 3d "primitivo" do Gamemaker :( .

### Describe the solution you'd like

Bem, levando em consideração o texto acima, acho que seria muito legal vocês implementarem formas um pouco mais fáceis de fazer algo em 3d, creio também que isso faria mais pessoas a entrarem nessa comunidade incrível que temos, porém, sei que a própria linguagem é voltada para o 2d. 

### Describe alternatives you've considered

Peço desculpas, mas não sei quais alternativas escrever aqui.

### Additional context

Muito obrigado pela atenção, e por toda comunidade ativa. ;)

**Comment by iampremo** [comment]
Is your feature request related to a problem?
Hi, I started programming in Gamemaker a year or so ago and I think it's the best and easiest to understand, but I'm trying to implement something more elaborate, like a small 3d Top Down and even with different tutorials, I found it very Gamemaker's "primitive" 3d is complicated :( .

Describe the solution you'd like
Well, taking into account the text above, I think it would be really cool for you to implement slightly easier ways of doing something in 3D, I also believe that this would make more people join this incredible community that we have, however, I know that the language itself is facing the 2d.

Describe alternatives you've considered
I apologize, but I don't know what alternatives to write here.

Additional context
Thank you very much for your attention, and for the entire active community. ;)

**Comment by jackerley** [comment]
We are looking to improve our support for 3D.

**Comment by Kyu321** [comment]
Obrigado pela atenção! feliz 2024 ;)

Em qua., 3 de jan. de 2024 07:38, jackerley ***@***.***>
escreveu:
