### ISSUE TITLE
In-Game: Add GML functions gpu_get_depth/gpu_set_depth

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#194]
Amid all of the new and updated {{gpu_}} functions that were introduced in GMS2, there is a very certain omission: d3d_set_depth still has no equivalent.

The function has been particularly useful for games utilizing "sprite-stacking" technique (where "3d models" are created out of multiple layered images), but has also seen occasional use as a way to pass a little metadata to a shader without breaking the batch with a uniform change or resorting to making replicas of default drawing functions or trying to stick metadata into RGBA/XY.

Implementation is straightforward as this is a global variable that runtime continues to use internally when switching layers. I can also write a draft of the manual entries since the GMS1 entry was _not_ what people would usually want to use it for.

**Comment by Gamer-XP** [comment]
I need to for different reason: I use z-buffer to break drawing into multiple passes (BGs, Characters, Effects). d3d_set_depth allowed me to draw at any Z value easily before, but they removed it in GMS2. It was usedful for both optimization and cool effects that abused z-buffer ( like shilouttes )

**Comment by FoxyOfJungle** [comment]
I'm curious, it's already possible to define the depth with the matrix functions, no? 

```
// enable z test/write
gpu_set_ztestenable(true);
gpu_set_zwriteenable(true);
// set z (depth)
matrix_build(matrix_world, x, y, z...);
```

Can someone explain to me if there is any difference? 🤔

**Comment by Gamer-XP** [comment]
d3d_set_depth didn't break batching. It simply modified Z values for drawing. Right now, Z value = depth, but changing depth does nothing. I've encountered a huge ton of issues so far because I can't change Z value easily, not only z-buffer related. 
For example: I try to rotate sprite using a matrix, but because Z value is at some random place - I can't find a centre for rotation easily.

**Comment by DragoniteSpam** [comment]
In the past few years I've jumped through quite a lot of hoops to draw sprites with layer-independent 3D depth without a million batch breaks. A simple set of functions like these would make a lot of my code significantly easier.
