### ISSUE TITLE
Variable Fields in Instance Inspector shouldn't need to be "unlocked" to be edited first

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#20]
Ticket #208909

oliver.rendelmann@gmail.com
Monday 10:06
Feature Type: feat_change_ide
Description: Making a list of variables that are exposed to the Instance Inspector when making rooms is very helpful, but having to "unlock" each and every single one of them to make changes adds a lot of unnecessary friction.

In Unity you can just go in and edit variables in the Inspector because they are meant to be exposed to the level designer.

Right-click -> Reset to default might be a better option to restore default values.

**Comment by WangleLine** [comment]
I agree.
It'd be better if the IDE just showed us what variables were changed with a small visual indicator instead of this unlocking nonsense.

**Comment by Alphish** [comment]
Just for the record, there's a more upvoted FR #1015 for basically the same thing, so feel free to give that one your upvotes, and this one could be closed as a duplicate. ^^'

**Comment by Alphish** [comment]
@rwkay This one is a duplicate.

**Comment by rwkay** [comment]
duplicate - closing this one
