### ISSUE TITLE
Ability to use "base" keyword for constructed objects

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#215]
Ticket #201000
Feature Type: feat_addition_ingame
Description: Loving being able to use structs with constructors in game maker. As it is right now, inheritance and overrides are a little lacking because of being unable to refer to the base class that a struct inherits from.

As of now, you can call a base class's function by making the function static, and in the constructor of the child class, store that function in a variable, then call it from the overriden function:
function Bar() : Foo() constructor {
static FooAction = action;
static action = function() {
FooAction();
show_debug_message("Bar");
}
}

but it would be nice to be able to call the base classes function within a function as:

function action() {
base.action();
}

much like calling event_inherited() in gamemaker objects.
Benefit: Inheritance in structs would be considered as complete as other languages. Right now inheritance feels like a "on or off" where you can either override or not, and it would be beneficial for things like state machines to be able to refer to the base class to be able to expand functionality with an override function vs replace it. It would negate a lot of redundant code.
Link:

**Comment by KeeVeeGames** [comment]
Duplicate #1023

**Comment by Alphish** [comment]
@rwkay A duplicate.

**Comment by rwkay** [comment]
duplicate issue - closing this one

**Comment by tinkerer-red** [comment]
I'd like to add, that the only way currently to achieve getting the base constructor is either to manually declare it inside ever constructor's static your self, or through extensive string manipulation.

Though, if one just needed the parent constructor of the calling instance, thats as simple as a double static get
