### ISSUE TITLE
Allow accessors natively for global

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#400]
[Ticket #194462]

Feature Type: feat_change_ingame
Description: Allow global to natively support an accessor, similar to structs where you can do global[$ variable] = "value". This is already possible with the workaround:
var _g = global;
_g[$ variable] = "value";

however the following will not even compile:
global[$ variable] = "value";
Benefit: This will allow for clean, non-convoluted code.
Link:

**Comment by rwkay** [comment]
Fixed in 2024.2
