### ISSUE TITLE
Change variable definitions in sequence editor

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#407]
Requested in ticket [Ticket #194330]

 

Feature Type: feat_addition_ide
Description: Similar to the room editor. In the sequence editor it would be very useful to change variable definitions in the sequence editor for things like hitboxes. (knockback, damage etc)
Benefit: rather than using sequence_instance_override_object to replace the existing hitbox with another one with the desired variables they could be set up in advance.

**Comment by KeeVeeGames** [comment]
Duplicate #127

**Comment by YYDan** [comment]
Dupe, as you say, Collapsing multiple requests for this change all into the one report.
