### ISSUE TITLE
Instance variables within sequences

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#489]
User request message on ticket [Ticket #190681]

 

Feature Type: feat_addition_ide
Description: You can't edit instances variables of objects created within the sequence editor.
Benefit: Using sequences to add animations to GUI elements you need to edit default variables such as the text of a button. Under the current implementation you have to hard code a button object for each variation.

**Comment by YYDan** [comment]
Duplicate of #127 - collapsing multiple requests for this change all into the one report.
