### ISSUE TITLE
Add burst timer for particle editor

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#69]
Ticket #206779

Feature Type: feat_addition_ide
Description: I would like a burst timer in the particle editor. So that I can basically recreate the preview where it automatically bursts every x seconds but within the editor.
Benefit: I would be able to make particle systems that utilise a timed repeated burst,

**Comment by pkraif** [comment]
Added new functions `part_emitter_delay(ps,ind,delay_min,delay_max,delay_unit)` and `part_emitter_interval(ps,ind,interval_min,interval_max,interval_unit)` for the Aug 23 release. Using thse you can configure delay before an emitter burst first particles and interval between following bursts.
