### ISSUE TITLE
Ticket: #178467 - dragging text in the code editor

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#817]
Ticket: [Ticket #178467]

*Description:* In GMS1.4 it was possible to select text/code and drag it with the left mouse button in the code editor, like in MS word. I could not find this functionality in GMS2 however, and now I have to cut and copy the text instead.

*Benefit:* It would make editing code much more convenient.

**Comment by dsk80004** [comment]
Duplicate Requests:
(Most upvoted): https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/989
https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/817
https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/796

**Comment by rwkay** [comment]
duplicate issue - closing this one
