### ISSUE TITLE
Ticket: #177583 - Particle type Xscale increase and Yscale increase property's

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#836]
Ticket: [Ticket #177583]

*Description:* Being able to control scales individually would let us make more gfx faster, otherwise if you want a stretching sprite on just one axis you have to do it via an animated sprite.

*Benefit:* A sword slash gfx where a stretched romboid gets longer on the x axis and the y axis gets squashed

**Comment by pkraif** [comment]
Added new functions `part_type_size_x(ind,size_min,size_max,size_incr,size_wiggle)` and `part_type_size_y(ind,size_min,size_max,size_incr,size_wiggle)` for Aug 23 release. Using these you can control particle x and y scale separately.
