### ISSUE TITLE
Have an option to allow double-clicking an included file open the associated editor

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#840]
https://help.yoyogames.com/hc/en-us/community/posts/360010460717-Double-clicking-on-an-Included-File-should-open-the-file-in-the-default-program

Currently double clicking on an included file opens the included-file properties. Add an option to change this to open the default editor defined by the OS. so if you dbl-click an image, the users image editing application will open

**Comment by YYDan** [comment]
This is already implemented in GameMaker as of the 2023.8 release, so closing this one now.

You can right-click any Included File to see the "Open in..." command and you can also change the default action double-clicking an Included File will do in your Preferences:
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/15669932/7da7adc8-4f57-4d60-bf49-c48b76caf70b)
